name: Daily Update and FTP Upload

on:
  schedule:
    - cron: '0 2 * * *'  # Läuft jeden Tag um 2:00 UTC
  workflow_dispatch:  # Erlaubt manuelle Ausführung

jobs:
  update_and_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rasterio pandas numpy pyarrow geopandas

    - name: Run update script
      run: python add_data_to_parquet.py
      
    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Anpassen an den Pfad Ihrer generierten Datei
        server-dir: /waldbrandgefahr/data/  # Anpassen an den Zielpfad auf Ihrem Webserver