name: Daily Update with FTP Download and Upload

on:
  schedule:
    - cron: '0 2 * * *'  # Läuft jeden Tag um 2:00 UTC
  workflow_dispatch:  # Erlaubt manuelle Ausführung

jobs:
  update_and_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rasterio pandas numpy pyarrow geopandas lftp

    - name: Download from FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; get /waldbrandgefahr/data/pipeline/fireweather_archive_warnregions.parquet -o fireweather_archive_warnregions.parquet"

    - name: Run update script
      run: python your_script_name.py

    - name: Upload to FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; put -O /waldbrandgefahr/data/pipeline fireweather_archive_warnregions.parquet"